# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/CelestiCall/Hardwares/IPModules/Proto_Star/Proto_Star.srcs/sources_1/bd/CPU_system/ip/CPU_system_processing_system7_0_3/CPU_system_processing_system7_0_3.xci
# IP: The module: 'CPU_system_processing_system7_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CelestiCall/Hardwares/IPModules/Proto_Star/Proto_Star.gen/sources_1/bd/CPU_system/ip/CPU_system_processing_system7_0_3/CPU_system_processing_system7_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_system_processing_system7_0_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/CelestiCall/Hardwares/IPModules/Proto_Star/Proto_Star.srcs/sources_1/bd/CPU_system/ip/CPU_system_processing_system7_0_3/CPU_system_processing_system7_0_3.xci
# IP: The module: 'CPU_system_processing_system7_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CelestiCall/Hardwares/IPModules/Proto_Star/Proto_Star.gen/sources_1/bd/CPU_system/ip/CPU_system_processing_system7_0_3/CPU_system_processing_system7_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_system_processing_system7_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
