# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/CelestiCall/Hardwares/IPModules/Proto_Star/pynq-z2.xdc

# Block Designs: bd/CPU_system/CPU_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_system || ORIG_REF_NAME==CPU_system} -quiet] -quiet

# IP: bd/CPU_system/ip/CPU_system_processing_system7_0_3/CPU_system_processing_system7_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_system_processing_system7_0_3 || ORIG_REF_NAME==CPU_system_processing_system7_0_3} -quiet] -quiet

# IP: bd/CPU_system/ip/CPU_system_v_tpg_0_1/CPU_system_v_tpg_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_system_v_tpg_0_1 || ORIG_REF_NAME==CPU_system_v_tpg_0_1} -quiet] -quiet

# IP: bd/CPU_system/ip/CPU_system_auto_pc_1/CPU_system_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_system_auto_pc_1 || ORIG_REF_NAME==CPU_system_auto_pc_1} -quiet] -quiet

# IP: bd/CPU_system/ip/CPU_system_ps7_0_axi_periph_2/CPU_system_ps7_0_axi_periph_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_system_ps7_0_axi_periph_2 || ORIG_REF_NAME==CPU_system_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/CPU_system/ip/CPU_system_rst_ps7_0_100M_2/CPU_system_rst_ps7_0_100M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_system_rst_ps7_0_100M_2 || ORIG_REF_NAME==CPU_system_rst_ps7_0_100M_2} -quiet] -quiet

# IP: bd/CPU_system/ip/CPU_system_v_tc_0_2/CPU_system_v_tc_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_system_v_tc_0_2 || ORIG_REF_NAME==CPU_system_v_tc_0_2} -quiet] -quiet

# IP: bd/CPU_system/ip/CPU_system_v_axi4s_vid_out_0_2/CPU_system_v_axi4s_vid_out_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_system_v_axi4s_vid_out_0_2 || ORIG_REF_NAME==CPU_system_v_axi4s_vid_out_0_2} -quiet] -quiet

# IP: bd/CPU_system/ip/CPU_system_rgb2dvi_0_2/CPU_system_rgb2dvi_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_system_rgb2dvi_0_2 || ORIG_REF_NAME==CPU_system_rgb2dvi_0_2} -quiet] -quiet

# XDC: d:/CelestiCall/Hardwares/IPModules/Proto_Star/Proto_Star.gen/sources_1/bd/CPU_system/CPU_system_ooc.xdc
