# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CelestiCall/Hardwares/IPModules/Proto_Star/Proto_Star.srcs/sources_1/bd/CPU_system/ip/CPU_system_auto_pc_0/CPU_system_auto_pc_0.xci
# IP: The module: 'CPU_system_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CelestiCall/Hardwares/IPModules/Proto_Star/Proto_Star.gen/sources_1/bd/CPU_system/ip/CPU_system_auto_pc_0/CPU_system_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_system_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/CelestiCall/Hardwares/IPModules/Proto_Star/Proto_Star.srcs/sources_1/bd/CPU_system/ip/CPU_system_auto_pc_0/CPU_system_auto_pc_0.xci
# IP: The module: 'CPU_system_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CelestiCall/Hardwares/IPModules/Proto_Star/Proto_Star.gen/sources_1/bd/CPU_system/ip/CPU_system_auto_pc_0/CPU_system_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_system_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
