(part "MT46H128M16LFDD-48_IT_C_TR"
    (packageRef "BGA60C80P9X10_800X900X100")
    (interface
        (port "A1" (symbPinId 1) (portName "VSS_1") (portType INOUT))
        (port "A2" (symbPinId 2) (portName "DQ15") (portType INOUT))
        (port "A3" (symbPinId 3) (portName "VSSQ_1") (portType INOUT))
        (port "A7" (symbPinId 4) (portName "VDDQ_1") (portType INOUT))
        (port "A8" (symbPinId 5) (portName "DQ0") (portType INOUT))
        (port "A9" (symbPinId 6) (portName "VDD_1") (portType INOUT))
        (port "B1" (symbPinId 7) (portName "VDDQ_2") (portType INOUT))
        (port "B2" (symbPinId 8) (portName "DQ13") (portType INOUT))
        (port "B3" (symbPinId 9) (portName "DQ14") (portType INOUT))
        (port "B7" (symbPinId 10) (portName "DQ1") (portType INOUT))
        (port "B8" (symbPinId 11) (portName "DQ2") (portType INOUT))
        (port "B9" (symbPinId 12) (portName "VSSQ_2") (portType INOUT))
        (port "C1" (symbPinId 13) (portName "VSSQ_3") (portType INOUT))
        (port "C2" (symbPinId 14) (portName "DQ11") (portType INOUT))
        (port "C3" (symbPinId 15) (portName "DQ12") (portType INOUT))
        (port "C7" (symbPinId 16) (portName "DQ3") (portType INOUT))
        (port "C8" (symbPinId 17) (portName "DQ4") (portType INOUT))
        (port "C9" (symbPinId 18) (portName "VDDQ_3") (portType INOUT))
        (port "D1" (symbPinId 19) (portName "VDDQ_4") (portType INOUT))
        (port "D2" (symbPinId 20) (portName "DQ9") (portType INOUT))
        (port "D3" (symbPinId 21) (portName "DQ10") (portType INOUT))
        (port "D7" (symbPinId 22) (portName "DQ5") (portType INOUT))
        (port "D8" (symbPinId 23) (portName "DQ6") (portType INOUT))
        (port "D9" (symbPinId 24) (portName "TEST") (portType INOUT))
        (port "E1" (symbPinId 25) (portName "VSSQ_4") (portType INOUT))
        (port "E2" (symbPinId 26) (portName "UDQS") (portType INOUT))
        (port "E3" (symbPinId 27) (portName "DQ8") (portType INOUT))
        (port "E7" (symbPinId 28) (portName "DQ7") (portType INOUT))
        (port "E8" (symbPinId 29) (portName "LDQS") (portType INOUT))
        (port "E9" (symbPinId 30) (portName "VDDQ_5") (portType INOUT))
        (port "F1" (symbPinId 31) (portName "VSS_2") (portType INOUT))
        (port "F2" (symbPinId 32) (portName "UDM") (portType INOUT))
        (port "F3" (symbPinId 33) (portName "NC") (portType INOUT))
        (port "F7" (symbPinId 34) (portName "A13") (portType INOUT))
        (port "F8" (symbPinId 35) (portName "LDM") (portType INOUT))
        (port "F9" (symbPinId 36) (portName "VDD_2") (portType INOUT))
        (port "G1" (symbPinId 37) (portName "CKE") (portType INOUT))
        (port "G2" (symbPinId 38) (portName "CK") (portType INOUT))
        (port "G3" (symbPinId 39) (portName "CK#") (portType INOUT))
        (port "G7" (symbPinId 40) (portName "WE#") (portType INOUT))
        (port "G8" (symbPinId 41) (portName "CAS#") (portType INOUT))
        (port "G9" (symbPinId 42) (portName "RAS#") (portType INOUT))
        (port "H1" (symbPinId 43) (portName "A9") (portType INOUT))
        (port "H2" (symbPinId 44) (portName "A11") (portType INOUT))
        (port "H3" (symbPinId 45) (portName "A12") (portType INOUT))
        (port "H7" (symbPinId 46) (portName "CS#") (portType INOUT))
        (port "H8" (symbPinId 47) (portName "BA0") (portType INOUT))
        (port "H9" (symbPinId 48) (portName "BA1") (portType INOUT))
        (port "J1" (symbPinId 49) (portName "A6") (portType INOUT))
        (port "J2" (symbPinId 50) (portName "A7") (portType INOUT))
        (port "J3" (symbPinId 51) (portName "A8") (portType INOUT))
        (port "J7" (symbPinId 52) (portName "A10/AP") (portType INOUT))
        (port "J8" (symbPinId 53) (portName "A0") (portType INOUT))
        (port "J9" (symbPinId 54) (portName "A1") (portType INOUT))
        (port "K1" (symbPinId 55) (portName "VSS_3") (portType INOUT))
        (port "K2" (symbPinId 56) (portName "A4") (portType INOUT))
        (port "K3" (symbPinId 57) (portName "A5") (portType INOUT))
        (port "K7" (symbPinId 58) (portName "A2") (portType INOUT))
        (port "K8" (symbPinId 59) (portName "A3") (portType INOUT))
        (port "K9" (symbPinId 60) (portName "VDD_3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "340-242388-REEL")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Micron/MT46H128M16LFDD-48-ITC-TR?qs=taEdVNyAfdH9Uc4RiwxL6g%3D%3D")
    (property "Manufacturer_Name" "Micron")
    (property "Manufacturer_Part_Number" "MT46H128M16LFDD-48 IT:C TR")
    (property "Description" "DRAM MOBILE DDR 2G 128MX16 FBGA")
    (property "Datasheet_Link" "https://www.micron.com/-/media/client/global/documents/products/data-sheet/dram/mobile-dram/low-power-dram/lpddr/80-series/t89m_auto_lpddr.pdf?rev=f2b742cd54b841dd86c5e0c2a564daf7")
    (property "symbolName1" "MT46H128M16LFDD-48_IT_C_TR")
)
